replicaCount: 2

image:
  repository: sush24/mediawiki
  pullPolicy: IfNotPresent
  tag: "thoughtworks-v1"

service:
  type: LoadBalancer
  port: 8080
  targetport: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
